# Default Title of Site
title: Jumbo Jekyll Theme
# Description of the site used for default meta description
description: |-
  The Jumbo Jekyll Theme is used across all Linaro static sites.
# Destination of the Jekyll site upon build of site.  
destination: _site
# Permalink for the blog posts
permalink: /blog/:title/ 
# Syntax highlighter
highlighter: rouge
# Markdown flavour used by Jekyll to parse markdown.
markdown: kramdown
# Default character encoding
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Files Jekyll will ignore when building the static site.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache

# Sass Configuration for the site styles
sass:
    style: compressed
    load_paths:
        - assets/css
    
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy: 
    # Toggle compression of HTML
    compress_html: true
    # JS Path added to exclude to stop errors.
    exclude: ["assets/**/*.js"] 
    
# Permalink style to be used for paginating pages
paginate_path: /blog/:num/ 

# Jekyll Pagination V2 Configuration
pagination:
    enabled: true
    per_page: 5
    # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
    trail:
        before: 2
        after: 2
    # Reverse the order of paginated pages
    sort_reverse: true
    # Field to sort posts by when paginating
    sort_field: 'date'

# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false

# Jekyll defaults - used to set default front matter values to collections and posts
defaults:
  #  Set a default Social Media Image
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
      
# Jekyll Assets setup
assets:
  # Compress JS Assets - uses the uglifier plugin 
  compress:
        js: true
  # Autoprefixer default settings
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  # These are the paths to look for assets
  sources:
    - assets/js/
    - assets/images/
    - assets/css/
    
# Jekyll relative links plugin settings    
jekyll_relative_links:
    process_all_collections: true
    verbose: 1
    
plugins:
    - jekyll-assets
    - jekyll-seo-tag
